#spring:
#  datasource:
#    url: jdbc:mysql://192.168.1.193:3306/dhp?useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
#server:
#  port: 8888



spring:

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:







server:
  port: 8888
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

