#spring:
#  datasource:
#    url: jdbc:mysql://192.168.1.193:3306/dhp?useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
#server:
#  port: 8888


#
#spring:
#    password: 1234
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#  redis:
#    database: 0
#    host: 127.0.0.1
#    port: 6379
#    password:

#  datasource:
#    url: jdbc:oracle:thin:@192.168.1.250:1521:orcl
#    username: rtm
#    password: rtm
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#  redis:
#    database: 0
#    host: 127.0.0.1
#    port: 6379
#    password:
#spring:
#  datasource:
#    url: jdbc:oracle:thin:@127.0.0.1:1521:rtm
#    username: rtm



  server:
    port: 8888




