#spring:
#  datasource:
#    url: jdbc:mysql://192.168.1.193:3306/dhp?useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
#server:
#  port: 8888



spring:
  output:
    ansi:
      enabled: always
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.117.132:3306/master?characterEncoding=utf-8
    username: root
    password: 123456
  db:
    readsize: 2
    read0:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.117.132:3306/salve1?characterEncoding=utf-8
      username: root
      password: 123456

    read1:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.117.132:3306/salve2?characterEncoding=utf-8
      username: root
      password: 123456
  profiles:
    active: dev
  redis:
    host: 192.168.117.132
  rabbitmq:
    host: 192.168.117.132
    port: 5672
    username: admin
    password: admin
    publisher-confirms: true
    listener:
      simple:
        concurrency: 10
        max-concurrency: 20
        prefetch: 5


server:
  tomcat:
    uri-encoding: utf-8
mybatis:
    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:mybatis/mapper/*.xml


aop:
    auto: true
    proxy-target-class: true
dl:
  response:
    enabled: true


